# Generated by Django 5.1.4 on 2025-06-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='impact_environnement',
            field=models.BooleanField(verbose_name="Impacts sur l'environnement"),
        ),
    ]
